/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedWorkspaceDashboardImport } from './routes/_authenticated/_workspace/dashboard'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const AuthenticatedWorkspaceLazyImport = createFileRoute(
  '/_authenticated/_workspace',
)()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedWorkspaceLazyRoute = AuthenticatedWorkspaceLazyImport.update(
  {
    id: '/_workspace',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/_workspace.lazy').then((d) => d.Route),
)

const AuthenticatedWorkspaceDashboardRoute =
  AuthenticatedWorkspaceDashboardImport.update({
    path: '/dashboard',
    getParentRoute: () => AuthenticatedWorkspaceLazyRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_workspace': {
      preLoaderRoute: typeof AuthenticatedWorkspaceLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_workspace/dashboard': {
      preLoaderRoute: typeof AuthenticatedWorkspaceDashboardImport
      parentRoute: typeof AuthenticatedWorkspaceLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRoute.addChildren([
    AuthenticatedWorkspaceLazyRoute.addChildren([
      AuthenticatedWorkspaceDashboardRoute,
    ]),
  ]),
  LoginLazyRoute,
])

/* prettier-ignore-end */
